version: "3.9"
services:
 web:
    build: ./.docker
    container_name: rgi_web
    volumes:
      - ./:/var/www/html/
      - ./.docker/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80"